// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'DeliverAny': typeof import("../components/deliver-any.vue")['default'],
    'FooterBar': typeof import("../components/footer-bar.vue")['default'],
    'LandingPage': typeof import("../components/landing-page.vue")['default'],
    'Location': typeof import("../components/location.vue")['default'],
    'NavBar': typeof import("../components/nav-bar.vue")['default'],
    'OtherMeals': typeof import("../components/other-meals.vue")['default'],
    'SpecialsToday': typeof import("../components/specials-today.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyDeliverAny': typeof import("../components/deliver-any.vue")['default'],
    'LazyFooterBar': typeof import("../components/footer-bar.vue")['default'],
    'LazyLandingPage': typeof import("../components/landing-page.vue")['default'],
    'LazyLocation': typeof import("../components/location.vue")['default'],
    'LazyNavBar': typeof import("../components/nav-bar.vue")['default'],
    'LazyOtherMeals': typeof import("../components/other-meals.vue")['default'],
    'LazySpecialsToday': typeof import("../components/specials-today.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const DeliverAny: typeof import("../components/deliver-any.vue")['default']
export const FooterBar: typeof import("../components/footer-bar.vue")['default']
export const LandingPage: typeof import("../components/landing-page.vue")['default']
export const Location: typeof import("../components/location.vue")['default']
export const NavBar: typeof import("../components/nav-bar.vue")['default']
export const OtherMeals: typeof import("../components/other-meals.vue")['default']
export const SpecialsToday: typeof import("../components/specials-today.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyDeliverAny: typeof import("../components/deliver-any.vue")['default']
export const LazyFooterBar: typeof import("../components/footer-bar.vue")['default']
export const LazyLandingPage: typeof import("../components/landing-page.vue")['default']
export const LazyLocation: typeof import("../components/location.vue")['default']
export const LazyNavBar: typeof import("../components/nav-bar.vue")['default']
export const LazyOtherMeals: typeof import("../components/other-meals.vue")['default']
export const LazySpecialsToday: typeof import("../components/specials-today.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
